package com.guilherme.desafiointer.remessa.exception;

public class UsuarioNotFoundException extends RemessaException {
    public UsuarioNotFoundException(String message) {
        super(message);
    }
}